[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mypackage"
version = "0.1.0"
description = "Простий демонстраційний Python-пакет"
authors = [{name="Vlad Ia"}]
readme = "README.md"
requires-python = ">=3.8"
